### ISSUE TITLE
CUDA 10.1 support?

### ISSUE THREAD

**Issue by vatai** [tensorflow/custom-op#15]
I can build and test the custom op in the container, but I can't use it outside of my container. Apparently the CUDA versions don't match.

```
$ python -c 'import tensorflow as tf; tf.load_op_library("./_time_two_ops.so")' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.10.0: cannot open shared object file: No such file or directory
```
Will this be fixed? What is the proper course of action in these situations? I have it figured out (sort of), how I will run my code through a container etc, but wanted to check, what is the "proper reaction" to these errors?

**Comment by yifeif** [comment]
The error you are seeing sounds independent from the custom op. The latest TensorFlow official pip packages were build with cuda 10 https://github.com/tensorflow/tensorflow/releases/tag/v1.13.1. You will need to build tf from source if you want 10.1 support.

For custom op, currently the CUDA version is hard-coded in configure.sh. Feel free to update those accordingly.

**Comment by vatai** [comment]
@yifeif Thank you reply. Such instructions might be nice in the guide, no? I'd be happy to write it, but I'd like to know I have the right idea: so to make a custom op for TensorFlow (with a different TF version and CUDA than the prebuilt/pip one) I'd have to do the following:

1. Build TF as described here: https://www.tensorflow.org/install/source#docker_linux_builds
2. Do the instructions from custom-op in the container from the previous step

Is this correct?

**Comment by yifeif** [comment]
That is correct. Though I think point 1 deviates from the audience of this guide, which is targeted at users who want to build custom op pip package that is compatible with TensorFlow's official pip release. That being said, I would prefer not pointing people to building TF from source in this repo (in fact, this guide is to allow users to not build from source). Let me know if you think this is reasonable. Thanks!

**Comment by vatai** [comment]
Ah I see/understand. In that case it really would deviate from the goal of the repo, and after rereading the README I see it clearly in the first paragraph. I guess custom-op pretty much qualifies as "tinkering under the hood", and if that is the case, chances are that the person reading this might also be interested in compiling from source, and that's why I had this suggestion. I'll see how everything works out, I also might end up not needing to compile from source - but if I do, I'll try to document my efforts and give more concrete suggestions.

Until then, thanks for the help!
