### ISSUE TITLE
GPU Kernel not executed

### ISSUE THREAD

**Issue by vatai** [tensorflow/custom-op#16]
It seems the `time_two_ops` kernel compiles (with warnings) but it seems the GPU kernel is not executed.

To reproduce the symptoms, change the multiplier from `2` to `3` i.e. in file `tensorflow_time_two/cc/kernels/time_two_kernels.cu.cc`, line 33 change `out[i] = 2 * ldg(in + i);` to `out[i] = 3 * ldg(in + i);`. Compile and run the `time_two_ops` test expecting a failure (because the test expects a times 2 multiplier), but the tests pass because the (unaltered) CPU kernel is executed.

Everything is run the docker, and I verified that cuda/tensorflow sees the GPU
```python
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```
indicates that the GPUs are detected from the container.

As far as I can tell, I'm following the guide/readme to the letter.

**Comment by yifeif** [comment]
Thanks for raising the issue @vatai!
I'll send a PR to force the test to run on GPU.
