### ISSUE TITLE
Unable to build pip package for python 3.7 using docker container

### ISSUE THREAD

**Issue by justin1121** [tensorflow/custom-op#25]
If I install python 3.7 using miniconda on the custom op docker container and then run `configure.sh` I get the following error:

```
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /root/miniconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
```

Is python 3.7 not supported in this docker container?

Thanks!

**Comment by seanpmorgan** [comment]
Just for visibility Addons is also tracking this:
https://github.com/tensorflow/addons/issues/75

AFAIK there is a new build env that is on the horizon which should be out somewhat soon.

**Comment by justin1121** [comment]
Thanks @seanpmorgan !

**Comment by yifeif** [comment]
I assume this is now fixed with the Ubuntu 16 images (please refer to the latest README.md). Please feel free to reopen if that’s not the case. Thanks!

**Comment by justin1121** [comment]
Great!
