### ISSUE TITLE
XLA custom op?

### ISSUE THREAD

**Issue by xerothermic** [tensorflow/custom-op#27]
I'm curious if there is any known limitation to compile external custom-op for XLA device (i.e. XLA_GPU)?

It looks to me instead of register Device(DEVICE_GPU) one could try Device(XLA_GPU) but I'm not sure if it will work. Can someone please comment?

**Comment by yifeif** [comment]
Thanks for the question @xerothermic. However this is out of the scope of this repo. Could you try posting it in the main tensorflow/tensorflow repo?
