### ISSUE TITLE
tensorflow serving with custom-op

### ISSUE THREAD

**Issue by dustindorroh** [tensorflow/custom-op#3]
What is the cleanest way to get a custom-op working with tensorflow serving? I have a working custom operation, but I'm having trouble getting tensorflow serving to load it. 

Thank you!

**Comment by dustindorroh** [comment]
I'm not sure if my issues is within the scope of this project, but I also asked the same question here:
https://stackoverflow.com/questions/53347789/how-to-use-custom-operations-with-tensorflow-server

**Comment by yifeif** [comment]
Hi @dustindorroh, sorry for the delay. I saw you posted your solution at the stackoverflow question linked. I added a comment there. Closing this. Thanks!

**Comment by r-mirchandani** [comment]
I'm struggling with a similar problem at the moment, and have followed the tips you posted about in the stackoverflow question. While everything builds fine, and the proper wrappers are generated for Python, using the Op throws an error regarding the Op still not being registered with my binary.

Did you have any ideas based on your experience on why this might still be happening?

**Comment by PayneJoe** [comment]
Hi, @r-mirchandani @dustindorroh do you have any improvement on this? I also want to add custom ops on tfserving, unfortunately not have a complete steps. Maybe some elaborate examples on this would be better?

**Comment by seanpmorgan** [comment]
Latest update can be seen here:
https://github.com/tensorflow/serving/issues/1381
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/custom_op.md

**Comment by PayneJoe** [comment]
> Latest update can be seen here:
> [tensorflow/serving#1381](https://github.com/tensorflow/serving/issues/1381)
> https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/custom_op.md

Great! Very informative!
