### ISSUE TITLE
Enable template repository

### ISSUE THREAD

**Issue by damienpontifex** [tensorflow/custom-op#30]
If this is meant to be a guide/template for developing custom ops, would it be worth enabling the GitHub [Template Repository setting](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/)?

I think it indicates well that people should use this as a base and makes it easy to do so.

**Comment by yifeif** [comment]
Thanks @damienpontifex! I’ve enabled the template repository setting.
