### ISSUE TITLE
Does this guide also apply to TF2.0?

### ISSUE THREAD

**Issue by steven-johnson** [tensorflow/custom-op#35]
It's not clear from the README if the guide, Docker image, etc. are set up for TF1, TF2, or both. Ideally both would be supported; but I'd settle for explicit documentation as to what is (and is not) supported at present.

**Comment by yifeif** [comment]
Great question @steven-johnson! It works for TF2.0. The only difference is that 2.0 (or any pip packages released after Aug 1, 2019) uses the newer tool chain, so you'd want to use the Ubuntu16 dockerfiles. Hope this clears it up.

**Comment by steven-johnson** [comment]
It does! (May I suggest you add this advice to the README?)

**Comment by steven-johnson** [comment]
Followup: Is the custom-op API identical for TF1.x and TF2.x? (i.e., if I build a custom op for one, can I expect it to work as-is in the other, assuming the same C++ toolchains, libc version, etc?) (And could the answer be explicitly added to the documentation for custom ops?)

**Comment by agostini01** [comment]
Because of eager execution, the steps for testing the custom op are different. You can try it with the `tensorflow/tensorflow:nightly-custom-op-ubuntu16` docker image

Start docker image
```
docker pull tensorflow/tensorflow:nightly-custom-op-ubuntu16
docker run -it --rm tensorflow/tensorflow:nightly-custom-op-ubuntu16 /bin/bash
```

Inside docker
```
git clone https://github.com/tensorflow/custom-op.git
cd custom-op
```

Build the pip package with bazel
```
./configure.sh
bazel build build_pip_pkg
bazel-bin/build_pip_pkg artifacts
```

Install the pip package
```
pip install artifacts/*.whl
```

*Test the package*
```
cd .. # Super important, otherwise python can't see the tensorflow_zero_out kernel
python -c "import tensorflow as tf;import tensorflow_zero_out as myop;print(myop.zero_out([[1,2], [3,4]]))"
```

**Comment by steven-johnson** [comment]
Thanks for the tip! 

I am also going to need to be testing this inside the Google TF environment (which has a quite different build set-up); if any Googlers reading this can comment (either here or privately) I would appreciate it.

**Comment by Durgesh93** [comment]
> Great question @steven-johnson! It works for TF2.0. The only difference is that 2.0 (or any pip packages released after Aug 1, 2019) uses the newer tool chain, so you'd want to use the Ubuntu16 dockerfiles. Hope this clears it up.

Hi I am trying to create a C++ custom op for tensorflow 1.13 version. Is there any way to specify the version 1.1x or it only works of tf 2.x. Please clarify.

**Comment by yifeif** [comment]
I've added a table in the README for the Docker image to use for corresponding TF version. Hope this helps!
