### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/dt7/usr/bin/gcc'

### ISSUE THREAD

**Issue by shengyushen** [tensorflow/custom-op#45]
I am using 
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
Cuda compilation tools, release 10.0, V10.0.130
print>>> print(tf.__version__)
1.15.2

I got the following error  when running "bazel build build_pip_pkg --verbose_failures":
++++++++++++++++++++++++++++++++++++++++++++++++++++++
WARNING: /root/.cache/bazel/_bazel_root/8538317fd780b9092f73dd9691ce04d0/external/local_config_tf/BUILD:7167:1:
target 'libtensorflow_framework.so' is both a rule and a file; please choose another name for the rule
INFO: Analysed target //:build_pip_pkg (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /root/ssy/custom-op/tensorflow_zero_out/BUILD:10:1: C++ compilation of rule '//tensorflow_zero_out:python
/ops/_zero_out_ops.so' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/8538317fd780b9092f73dd9691ce04d0/execroot/__main__ && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/lib/x86_64-linux-gnu \
    LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64 \
    PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
\
    PWD=/proc/self/cwd \
    TF_CUDA_VERSION=10.0 \
    TF_CUDNN_VERSION=7 \
    TF_HEADER_DIR=/usr/local/lib/python3.5/dist-packages/tensorflow_core/include \
    TF_NEED_CUDA=1 \
    TF_SHARED_LIBRARY_DIR=/usr/local/lib/python3.5/dist-packages/tensorflow_core \
    TF_SHARED_LIBRARY_NAME=libtensorflow_framework.so.1 \
  third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0/clang/bin/crosstool_wrapper_driv
er_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow_zero_out/_objs/python/ops/_zero_out_ops.so/zero_out_ops.pi
c.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow_zero_out/_objs/python/ops/_zero_out_ops.so/zero_out_ops.pic.o
' -iquote . -iquote bazel-out/k8-opt/genfiles -iquote bazel-out/k8-opt/bin -iquote external/local_config_tf -iqu
ote bazel-out/k8-opt/genfiles/external/local_config_tf -iquote bazel-out/k8-opt/bin/external/local_config_tf -iq
uote external/bazel_tools -iquote bazel-out/k8-opt/genfiles/external/bazel_tools -iquote bazel-out/k8-opt/bin/ex
ternal/bazel_tools -isystem external/local_config_tf/include -isystem bazel-out/k8-opt/genfiles/external/local_c
onfig_tf/include -isystem bazel-out/k8-opt/bin/external/local_config_tf/include '-std=c++11' -Wno-builtin-macro-
redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '
-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-syste
m-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -pthread '-std=c++11' '-D_GLIBCXX_USE_CXX11_ABI=0
' -c tensorflow_zero_out/cc/ops/zero_out_ops.cc -o bazel-out/k8-opt/bin/tensorflow_zero_out/_objs/python/ops/_ze
ro_out_ops.so/zero_out_ops.pic.o)
Execution platform: @bazel_tools//platforms:host_platform
Traceback (most recent call last):
  File "third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0/clang/bin/crosstool_wrappe
r_driver_is_not_gcc", line 267, in <module>
    sys.exit(main())
  File "third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010-nvcc-cuda10.0/clang/bin/crosstool_wrappe
r_driver_is_not_gcc", line 264, in main
    return subprocess.call([CPU_COMPILER] + cpu_compiler_flags)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/dt7/usr/bin/gcc'
Target //:build_pip_pkg failed to build
INFO: Elapsed time: 0.466s, Critical Path: 0.18s

++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by yifeif** [comment]
@shengyushen was this running inside the provided Docker container?

**Comment by yifeif** [comment]
@shengyushen, docker image `tensorflow/tensorflow:2.1.0-custom-op-gpu-ubuntu16` should contain these missing files. Feel free to re-open this if you are still seeing issues. Thank you.

**Comment by prouast** [comment]
I ran into the same problem building a custom op for `tensorflow/tensorflow:latest-gpu` Docker container.  You can avoid the problem by building via make instead.
