### ISSUE TITLE
Errors creating pip package on windows

### ISSUE THREAD

**Issue by michele-arrival** [tensorflow/custom-op#49]
Hi, I've been experimenting with this on Windows 10 (TF version 1.15.2 - Python 3.7 - VS-2017, cuda 10.0)  and i'm stuck with creating the pip package.

The instructions say that 2 commands should suffice:

```
bazel build :build_pip_pkg
```

followed by 

```
bazel-bin/build_pip_pkg artifacts
```

The first command runs through without problem. After 1 small change (compilation flag for VS 2017), the packages are built.
For the second command I have to run ` "bazel-bin/build_pip_pkg" artifacts` for it to run, but either way i then face this error:

> cp: cannot stat 'bazel-bin/build_pip_pkg.runfiles/__main__/setup.py': No such file or directory

There's no `build_pip_pkg.runfiles/__main__` folder created at all. 

the folder bazel-bin looks like this:

```
.
├── build_pip_pkg.exe.runfiles
├── external
├── tensorflow_time_two
├── tensorflow_zero_out
├─build_pip_pkg
├─build_pip_pkg.exe
└─build_pip_pkg.exe.runfiles_manifest
```

Seems a problem with version of bazel, but I've tried with several versions of bazel (0.24.1, 0.25.2, 0.26.1, 1.2.1, 2.1.0) and none works.

Weirdly enough, on linux docker image 16, there's no such problem (bazel 1.2.1, tf-1.15.2)

**Comment by michele-arrival** [comment]
I have the same problem with tensorflow 2.0.1

**Comment by jakline** [comment]
+Yifei Feng <yifeif@google.com>

**Comment by yifeif** [comment]
@michele-arrival do you mind syncing to head and adding `--enable_runfiles` option to your bazel build command?

**Comment by michele-arrival** [comment]
Hi @yifeif thank you very much for the update. That fixed it as far as the creation of the `__main__` folder is concerned.

Now I get another error from VS linker:

```
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120
```

after setting a debug flag for setuptools with 

```
set DISTUTILS_DEBUG=1
```

I see that the failing command is:

```
distutils.errors.LinkError: command ['"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe"', '/nologo', '/INCREMENTAL:NO', '/LTCG', '/DLL', '/MANIFEST:EMBED,ID=2', '/MANIFESTUAC:NO', '/LIBPATH:C:\\tools\\Anaconda3\\envs\\tf-dev-1.15\\libs', '/LIBPATH:C:\\tools\\Anaconda3\\envs\\tf-dev-1.15\\PCbuild\\amd64', '"/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\ATLMFC\\lib\\x64"', '"/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\lib\\x64"', '"/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\lib\\um\\x64"', '"/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\ucrt\\x64"', '"/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x64"', '"/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\ATLMFC\\lib\\x64"', '"/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\lib\\x64"', '"/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\ucrt\\x64"', '"/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.18362.0\\um\\x64"', '/EXPORT:PyInit__foo', 'build\\temp.win-amd64-3.7\\Release\\stub.obj', '/OUT:build\\lib.win-amd64-3.7\\_foo.cp37-win_amd64.pyd', '/IMPLIB:build\\temp.win-amd64-3.7\\Release\\_foo.cp37-win_amd64.lib'] failed with exit status 1120
```

The linker error does not occur and the whl is built correctly if i remove the line `ext_modules=[Extension('_foo', ['stub.cc'])],` from `setup.py`

happy to open another issue if necessary

**Comment by michele-arrival** [comment]
also after installing the whl, `_time_two_ops.so` does not get installed into `tensorflow_time_two\python\ops`. It's nowhere to be found in the site-packages tree

**Comment by yifeif** [comment]
Thanks for sending the PR! I remembering see the warning about the \. Yea, we can definitely remove those.

I just updated `setup.py` to remove the `stub.cc` hack we had.

**Comment by yifeif** [comment]
Was able to build the pip package at head with the change #51. Let me know if you are still seeing issues!

**Comment by michele-arrival** [comment]
all seems good now, thanks!

may i ask what's the reason for removing support for version 1.x?

**Comment by yifeif** [comment]
Glad to hear!
We haven't removed support for version 1.x. We still have docker images for v1. However, the head of the repo follows the latest of TF.

**Comment by Patrikvs94** [comment]
@yifeif Hello, I'm running into a similar issue. I'm getting the current message and I have no idea what's wrong with my set-up. I've made sure I've got the right versions of stuff, MSVC2019 and Bazel 3.1.0. I'm running this on Windows 10.

C:\Users\patrik.veges\Desktop\custom-op>bazel-bin\build_pip_pkg artifacts
++ uname -s
++ tr A-Z a-z
+ PLATFORM=msys_nt-10.0-19041
+ is_windows
+ [[ msys_nt-10.0-19041 =~ (cygwin|mingw32|mingw64|msys)_nt* ]]
+ true
+ PIP_FILE_PREFIX=bazel-bin/build_pip_pkg.exe.runfiles/__main__/
+ main artifacts
+ [[ ! -z artifacts ]]
+ [[ artifacts == \m\a\k\e ]]
+ DEST=artifacts
+ shift
+ [[ ! -z '' ]]
+ [[ -z artifacts ]]
+ mkdir -p artifacts
+ [[ msys_nt-10.0-19041 == \d\a\r\w\i\n ]]
++ readlink -f artifacts
+ DEST=/c/Users/patrik.veges/Desktop/custom-op/artifacts
+ echo '=== destination directory: /c/Users/patrik.veges/Desktop/custom-op/artifacts'
=== destination directory: /c/Users/patrik.veges/Desktop/custom-op/artifacts
++ mktemp -d -t tmp.XXXXXXXXXX
+ TMPDIR=/tmp/tmp.jzfniKoxJs
++ date
+ echo Mon Sep 14 16:30:07 WEST 2020 : '=== Using tmpdir: /tmp/tmp.jzfniKoxJs'
Mon Sep 14 16:30:07 WEST 2020 : === Using tmpdir: /tmp/tmp.jzfniKoxJs
+ echo '=== Copy TensorFlow Custom op files'
=== Copy TensorFlow Custom op files
+ cp bazel-bin/build_pip_pkg.exe.runfiles/__main__/setup.py /tmp/tmp.jzfniKoxJs
cp: cannot stat 'bazel-bin/build_pip_pkg.exe.runfiles/__main__/setup.py': No such file or directory
