### ISSUE TITLE
Cuda Configuration Error: Failed to run find_cuda_config.py

### ISSUE THREAD

**Issue by Eunhui-Kim** [tensorflow/custom-op#58]
I run docker container with docker img - tensorflow 1.15.2 gpu py3 on ubuntu 16.04
In the img, 
tensorflow 1.15.2, and (gcc, g++ 7.4.0), python 3.6.9(gcc 8.3.0),  
After I success build my_custom_op, 
I tried to build pip tensorflow package according to the guide of custom-op github
such as running 'bazel build :build_pip_pkg'.
But I met the following error.

ROR: Analysis of target '//:build_pip_pkg' failed; build aborted: error loading package 'tensorflow_active_shift': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "/work_dir/gpu/cuda_configure.bzl", line 1254
                _create_local_cuda_repository(repository_ctx)
        File "/work_dir/gpu/cuda_configure.bzl", line 985, in _create_local_cuda_repository
                _get_cuda_config(repository_ctx)
        File "/work_dir/gpu/cuda_configure.bzl", line 714, in _get_cuda_config
                find_cuda_config(repository_ctx, ["cuda", "cudnn"])
        File "/work_dir/gpu/cuda_configure.bzl", line 694, in find_cuda_config
                auto_configure_fail(("Failed to run find_cuda_config...))
        File "/work_dir/gpu/cuda_configure.bzl", line 325, in auto_configure_fail
                fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any cublas_api.h in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/usr/local/cuda'

INFO: Elapsed time: 0.162s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

My system is ubuntu 16.04
and gpu is rtx2080, the container cuda vers. is 10.0 and the solution patch on the find_cuda_config.py already applied for the similar error for cuda 10.1.

When I tried to find the file ' cublas_api.h ' from the root such as 'find / -name cublas_api.h', I cannot find the file.
However, the original ubuntu system of mine is installed cuda 10.2 and I can find the cublas_api.h.

How can I solve this problem?
Thank you in advance

**Comment by 372046933** [comment]
According to the doc, TF1.5 should use `custom-op-gpu-ubuntu16`

**Comment by Eunhui-Kim** [comment]
I do not use docker. 
After I add pip-package in make file as follows,
I can success build pip-package by make pip_pkg not bazel. 

pip_pkg: $(SHIFT_TARGET_LIB)
    ./build_pip_pkg.sh make artifacts
