### ISSUE TITLE
Building pip pkg for different architectures (OSX vs Ubu)

### ISSUE THREAD

**Issue by sbsends** [tensorflow/custom-op#7]
Is there any documentation on using bazel to build pip pkgs for different architectures? The compiled custom-op.so contains different ELF headers.

**Comment by sbsends** [comment]
@yifeif

**Comment by yifeif** [comment]
What platform are you trying to build on? Currently this guide is tailored for ubuntu.

**Comment by sbsends** [comment]
I was able to build the ops on a mac by slightly modifying the build_pip_pkg.sh file.  Mac does not support `readlink -f`. 

```bash
# build_pip_pkg.sh

  mkdir -p ${DEST}
  DEST=$(pwd)/${DEST}
  echo "=== destination directory: ${DEST}"
```

Is there anyway to cross-compile the ops using Bazel instead of switching machines? I would like to build and publish the ops for linux/mac using C.I. instead of manually building on different machines.

Thanks!

**Comment by yifeif** [comment]
Glad you got it working.
This sounds like a bazel question :). I think you can use the --platforms flag https://docs.bazel.build/versions/master/platforms.html#specifying-a-platform-for-a-build
