### ISSUE TITLE
tensorflow/tensorflow:custom-op-gpu-ubuntu16 only installed tensorflow-cpu version

### ISSUE THREAD

**Issue by BruceDai003** [tensorflow/custom-op#74]
I tried `docker pull tensorflow/tensorflow:custom-op-gpu-ubuntu16` and run it.
Then tried `'./configure.sh'`
However, it detected that no `tensorflow-gpu` is installed in this container, and has to uninstall the already installed tensorflow and install a` tensorflow-gpu` version. Shouldn't your docker image already has `tensorflow-gpu` installed?

**Comment by bhack** [comment]
Yes it is a bug with the new naming. See https://github.com/tensorflow/tensorflow/issues/43022#issuecomment-688735058

**Comment by bhack** [comment]
Check also https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/Dockerfile.custom_op_ubuntu_16_cuda10.0#L78

**Comment by bhack** [comment]
There is a PR at https://github.com/tensorflow/custom-op/pull/79
