### ISSUE TITLE
Building custom ops on Windows, tf header include failing

### ISSUE THREAD

**Issue by Patrikvs94** [tensorflow/custom-op#78]
I'm trying to build the example files on Windows, but I keep getting the same error after following the tutorial several times. Bash keeps telling me the following:

Code snippet:
-------------------------------------------------------

$ bazel build tensorflow_zero_out:python/ops/_zero_out_ops.so
Loading:
Loading: 0 packages loaded
Analyzing: target //tensorflow_zero_out:python/ops/_zero_out_ops.so (0 packages loaded, 0 targets configured)
INFO: Analyzed target //tensorflow_zero_out:python/ops/_zero_out_ops.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 5] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: C:/users/patrik.veges/_bazel_patrik.veges/gd5nvtb3/external/local_config_tf/BUILD:17:8: Executing genrule @local_config_tf//:tf_header_include failed (Exit 35584)
      0 [] bash 465 cygwin_exception::open_stackdumpfile: Dumping stack trace to bash.exe.stackdump
Target //tensorflow_zero_out:python/ops/_zero_out_ops.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/users/patrik.veges/_bazel_patrik.veges/gd5nvtb3/external/local_config_tf/BUILD:3:11 Executing genrule @local_config_tf//:tf_header_include failed (Exit 35584)
INFO: Elapsed time: 1.299s, Critical Path: 1.19s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by bhack** [comment]
Is this the same as https://github.com/tensorflow/custom-op/issues/78?

**Comment by bhack** [comment]
Is this the same as https://github.com/tensorflow/tensorflow/issues/43022?

**Comment by bhack** [comment]
Please close this is a duplicated of https://github.com/tensorflow/custom-op/issues/74

**Comment by bhack** [comment]
https://github.com/tensorflow/custom-op/pull/79

**Comment by Patrikvs94** [comment]
Hi again @bhack . I managed to build it on Windows now, however now the "bazel-bin/build_pip_pkg artifacts" doesn't generate anything. I get the follow command line info.

`$ bazel-bin/build_pip_pkg artifacts
++ uname -s
++ tr A-Z a-z
+ PLATFORM=mingw64_nt-10.0-19041
+ is_windows
+ [[ mingw64_nt-10.0-19041 =~ (cygwin|mingw32|mingw64|msys)_nt* ]]
+ true
+ PIP_FILE_PREFIX=bazel-bin/build_pip_pkg.exe.runfiles/__main__/
+ main artifacts
+ [[ ! -z artifacts ]]
+ [[ artifacts == \m\a\k\e ]]
+ DEST=artifacts
+ shift
+ [[ ! -z '' ]]
+ [[ -z artifacts ]]
+ mkdir -p artifacts
+ [[ mingw64_nt-10.0-19041 == \d\a\r\w\i\n ]]
++ readlink -f artifacts
+ DEST=/c/Users/patrik.veges/Desktop/custom-op/artifacts
+ echo '=== destination directory: /c/Users/patrik.veges/Desktop/custom-op/artifacts'
=== destination directory: /c/Users/patrik.veges/Desktop/custom-op/artifacts
++ mktemp -d -t tmp.XXXXXXXXXX
+ TMPDIR=/tmp/tmp.fRga9SMi64
++ date
+ echo 14 Sep 2020 15:47:39 : '=== Using tmpdir: /tmp/tmp.fRga9SMi64'
14 Sep 2020 15:47:39 : === Using tmpdir: /tmp/tmp.fRga9SMi64
+ echo '=== Copy TensorFlow Custom op files'
=== Copy TensorFlow Custom op files
+ cp bazel-bin/build_pip_pkg.exe.runfiles/__main__/setup.py /tmp/tmp.fRga9SMi64
cp: cannot stat 'bazel-bin/build_pip_pkg.exe.runfiles/__main__/setup.py': No such file or directory
`

**Comment by bhack** [comment]
I think that this is another issue. Please close this and open a new one directly at https://github.com/tensorflow/custom-op

**Comment by mareikethies** [comment]
@Patrikvs94 Did the fix with the package naming solve your first issue? I experience the same thing even when using the updated configure.sh
