### ISSUE TITLE
Centralize copts within repostiory

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/custom-op#8]
Currently the compiler flags are stored [in the BUILD file](https://github.com/tensorflow/custom-op/blob/master/tensorflow_zero_out/BUILD#L16) of the custom op.  This becomes difficult to maintain if there are many op directories in a repository. It also makes it difficult for customized builds specific to the OS and architecture (e.g. conda or gentoo linux).

Seeing as custom-op is used as a template this may be worth restructuring?

cc @perfinion

**Comment by yifeif** [comment]
I'm all up for it. We can maybe have a repo with only the bazel macros that other add-on repos can import from.

**Comment by seanpmorgan** [comment]
I believe this is under consideration as a SIG build repository. Closing issue unless there is more to discuss.
